[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
contextPath = "backend"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
