[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
# Ensure prisma generate runs right before starting the app
cmd = "npx prisma generate && npm run start:prod"
